# Generated by Django 4.1.5 on 2023-01-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_topping_orders_coffee_coffee_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_coasts',
            field=models.FloatField(null=True),
        ),
    ]
